### ISSUE TITLE
bad link

### ISSUE THREAD

**Issue by robertschulman1** [YevheniiKovryzhenko/RRTV_TiltWing#1]

**Comment by robertschulman1** [comment]
Jack - Howdy. Bob Schulman here. In your README, in the paragraph under "Integration with PX4", the first hyperlink is wrong: it gives a 404 error.

**Comment by YevheniiKovryzhenko** [comment]
Hi Bob, I think everything should be fixed now. I checked all links without a GitHub account at all, and they work correctly now. The only one you can't access is [VSDDL Control System and GCS package for RRTV](https://github.com/YevheniiKovryzhenko/RRTV_TiltWing_VSDDL_Packages.git), which is currently a private repository. I will add you there too.

**Comment by robertschulman1** [comment]
Jack,

Got it. Thanks!

bob

On 2024-09-10 11:39, Jack Kovryzhenko wrote:

> Hi Bob, I think everything should be fixed now. I checked all links 
> without a GitHub account at all, and they work correctly now. The only 
> one you can't access is VSDDL Control System and GCS package for RRTV 
> [1], which is currently a private repository. I will add you there too.
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/YevheniiKovryzhenko/RRTV_TiltWing_VSDDL_Packages.git
[2] 
https://github.com/YevheniiKovryzhenko/RRTV_TiltWing/issues/1#issuecomment-2341292829
[3]
